### ISSUE TITLE
Grid from projected XYZ mirrored

### ISSUE THREAD

**Issue by baharmon** [dbt-ethz/docofossor#3]
Hi, when I import XYZ point clouds into Docofossor from a projected CRS the resulting grid appears to be mirrored on the XZ plane. In the following example the point cloud is in NAD 1983 Louisiana South State Plane (EPSG 6478). Why is it mirroring? 
Thanks, Brendan

[elevation.xyz](https://github.com/baharmon/generative-design/raw/main/grasshopper/data/elevation.xyz)

[terrain-modeling.gh](https://github.com/baharmon/generative-design/raw/main/grasshopper/terrain-modeling.gh)

**Original DEM**
<img width="1920" alt="metashape" src="https://user-images.githubusercontent.com/10392927/113515500-8233b280-953a-11eb-9672-a5a1ae0320e1.png">

**Imported with Docofossor**
<img width="1916" alt="docofossor" src="https://user-images.githubusercontent.com/10392927/113515501-83fd7600-953a-11eb-8878-b483b2ecdfe1.png">

**Mirrored on XZ plane**
<img width="1919" alt="mirror" src="https://user-images.githubusercontent.com/10392927/113515504-85c73980-953a-11eb-896a-b3f25a0279ec.png">

**Comment by worbit** [comment]
Hi @baharmon 

thank you for your interest in Docofossor and for posting the question.
The reason why the landscape is imported "mirrored" is the way the **Import XYZ** component is expecting the values to be sorted. In our example file, the points are listed from left to right, bottom to top. So after the first row, the _y-value increases_: https://github.com/dbt-ethz/docofossor/blob/master/examples/example_DTM.xyz#L101
In your example, the points are sorted left to right, top to bottom. So after the first row, the _y-value decreases_ (line 801).
The easiest fix is indeed to mirror the mesh at a vertical plane, using standard Grasshopper components. Instead of the WorldXZ plane, I recommend using a plane containing the center of the mesh's bounding box, to preserve correct geolocation (if this is necessary).

**Comment by baharmon** [comment]
Thank you for the explanation and tips. Appreciate it.
